source 'https://rubygems.org'
gem 'rails', '4.1.1'
gem 'pg'
gem 'uglifier', '>= 1.3.0'
gem 'sass-rails'
gem 'coffee-rails'
gem 'carrierwave'
gem 'acts-as-taggable-on'
gem 'kaminari'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jquery-turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'spring',        group: :development
