Image.create!([
  {item_id: 1, image_layer: "1of2BuddingBeat-PeonyPink-Headphones.png"},
  {item_id: 2, image_layer: "1of2BuddingBeat-White-Headphones.png"},
  {item_id: 3, image_layer: "1of2CheckeredPuff-Purple-Scarf.png"},
  {item_id: 4, image_layer: "1of2CheckeredPuff-Red-Scarf.png"},
  {item_id: 5, image_layer: "1of2ElissasTresses-OrangeCaramel-Hairstyle.png"},
  {item_id: 6, image_layer: "1of2Rodeo-CherryRed-Boots.png"},
  {item_id: 7, image_layer: "1of2SkyeERCitizen-Navy-TracksuitJacket.png"},
  {item_id: 8, image_layer: "1of2SugarlessCandy-Lavender-PigtailsHairstyle.png"},
  {item_id: 1, image_layer: "2of2BuddingBeat-PeonyPink-Headphones.png"},
  {item_id: 2, image_layer: "2of2BuddingBeat-White-Headphones.png"},
  {item_id: 3, image_layer: "2of2CheckeredPuff-Purple-Scarf.png"},
  {item_id: 4, image_layer: "2of2CheckeredPuff-Red-Scarf.png"},
  {item_id: 5, image_layer: "2of2ElissasTresses-OrangeCaramel-Hairstyle.png"},
  {item_id: 6, image_layer: "2of2Rodeo-CherryRed-Boots.png"},
  {item_id: 7, image_layer: "2of2SkyeERCitizen-Navy-TracksuitJacket.png"},
  {item_id: 8, image_layer: "2of2SugarlessCandy-Lavender-PigtailsHairstyle.png"},
  {item_id: 9, image_layer: "Background_Equipable.png"},
  {item_id: 10, image_layer: "BehindTheBlossoms-Auburn-Eyes.png"},
  {item_id: 11, image_layer: "BehindTheBlossoms-Blush-Makeup.png"},
  {item_id: 12, image_layer: "BehindTheBlossoms-Chestnut-Eyebrows.png"},
  {item_id: 13, image_layer: "BehindTheBlossomsFloppy-Lavender-KnitSweater.png"},
  {item_id: 14, image_layer: "BehindTheBlossomsFloppy-Pink-KnitSweater.png"},
  {item_id: 15, image_layer: "BehindTheBlossoms-Lavender-Hairstyle.png"},
  {item_id: 16, image_layer: "BehindTheBlossoms-Pink-Hairstyle.png"},
  {item_id: 17, image_layer: "BehindTheBlossoms-Red-Glasses.png"},
  {item_id: 18, image_layer: "BehindTheBlues-SoftGray-Glasses.png"},
  {item_id: 19, image_layer: "BitOfABother-Mouth.png"},
  {item_id: 20, image_layer: "CalmingGaze-Eyes-GlassBlue.png"},
  {item_id: 21, image_layer: "CalmingGaze-SiennaBrown-Eyebrows.png"},
  {item_id: 22, image_layer: "CheekyGrin-Mouth.png"},
  {item_id: 23, image_layer: "CheerfulGlint-AshBrown-Eyebrows.png"},
  {item_id: 24, image_layer: "CheerfulGlint-SkyBlue-Eyes.png"},
  {item_id: 25, image_layer: "ChipperUpbeatNatural-ForestGreen-Eyes.png"},
  {item_id: 26, image_layer: "DecidedlySatisfiedSmile-Mouth.png"},
  {item_id: 27, image_layer: "Disappearing_Bra.png"},
  {item_id: 28, image_layer: "Disappearing_Briefs.png"},
  {item_id: 29, image_layer: "Disappearing_Panties.png"},
  {item_id: 30, image_layer: "DraconianRule-Crimson-Eyebrows.png"},
  {item_id: 31, image_layer: "DraconianRule-Crimson-Eyes.png"},
  {item_id: 32, image_layer: "FleepTheCloudsheep-HoveringPose.png"},
  {item_id: 33, image_layer: "GentlyCurious-Blush-Makeup.png"},
  {item_id: 34, image_layer: "GentlyCuriousGaze-AshBrown-Eyebrows.png"},
  {item_id: 35, image_layer: "GentlyCuriousGaze-LilypadGreen-Eyes.png"},
  {item_id: 36, image_layer: "GentlyCurious-Mouth.png"},
  {item_id: 37, image_layer: "GrumpySpectre-Indigo-Eyes.png"},
  {item_id: 38, image_layer: "GrumpySpectre-Indigo-Face.png"},
  {item_id: 39, image_layer: "HomecomingTrail-Background.png"},
  {item_id: 40, image_layer: "Mischeivous-Mouth.png"},
  {item_id: 41, image_layer: "MischeivousThought-AgateGreen-Eyes.png"},
  {item_id: 42, image_layer: "MischeivousThought-AshBrown-Eyebrows.png"},
  {item_id: 43, image_layer: "PeppyPreppy-Auburn-PonytailHairstyle.png"},
  {item_id: 44, image_layer: "PeppyPreppy-Raspberry-PonytailHairstyle.png"},
  {item_id: 45, image_layer: "Piqued-Mouth.png"},
  {item_id: 46, image_layer: "ReubenStyledSporty-PaleFawn-Hairstyle.png"},
  {item_id: 47, image_layer: "RolledCuff-MedBlue-Jeans.png"},
  {item_id: 48, image_layer: "SemiSheenLycra-Black-Tights.png"},
  {item_id: 49, image_layer: "SemiSheenLycra-Silver-Tights.png"},
  {item_id: 50, image_layer: "SereneKindess-Flushed-EyeshdwNBlushMakeup.png"},
  {item_id: 51, image_layer: "SereneKindess-SpokenGently-Mouth.png"},
  {item_id: 52, image_layer: "SereneKindness-OceanBlue-Eyes.png"},
  {item_id: 53, image_layer: "SereneKindness-RedBrown-Eyebrows.png"},
  {item_id: 54, image_layer: "ShyPeep-Mouth.png"},
  {item_id: 55, image_layer: "SkyeERCitizen-PeriwinkleNWhite-Blouse.png"},
  {item_id: 56, image_layer: "SkyeERCitizen-PeriwinkleNWhite-Loafers.png"},
  {item_id: 57, image_layer: "SkyeERCitizen-PeriwinkleNWhite-Skirt.png"},
  {item_id: 58, image_layer: "SkyeERCitizen-PeriwinkleNWhite-Stockings.png"},
  {item_id: 59, image_layer: "SkyeERCitizen-PinkNWhite-Blouse.png"},
  {item_id: 60, image_layer: "SkyeERCitizen-PinkNWhite-Shoes.png"},
  {item_id: 61, image_layer: "SkyeERCitizen-PinkNWhite-Skirt.png"},
  {item_id: 62, image_layer: "SkyeERCitizen-PinkNWhite-Stockings.png"},
  {item_id: 63, image_layer: "SkyeERCitizenUniform-Navy-DressShirt.png"},
  {item_id: 64, image_layer: "SkyeERCitizenUniform-Navy-Jacket.png"},
  {item_id: 65, image_layer: "SkyeERCitizenUniform-Navy-Loafers.png"},
  {item_id: 66, image_layer: "SkyeERCitizenUniform-Navy-Slacks.png"},
  {item_id: 67, image_layer: "SmilingToMyself-Mouth.png"},
  {item_id: 68, image_layer: "SpeakingContentedly-Mouth.png"},
  {item_id: 69, image_layer: "SugarlessCandy-LavenderDrop-HeartUGazeEyes.png"},
  {item_id: 70, image_layer: "TobiasHeroic-Brown-Hairstyle.png"},
  {item_id: 71, image_layer: "TomasSmooth-HighlightedChestnut-Hairstyle.png"},
  {item_id: 72, image_layer: "TrustingEyes-Gray-Eyebrows.png"},
  {item_id: 73, image_layer: "TrustingPeer-AgateGreen-Eyes.png"},
  {item_id: 74, image_layer: "TrustingPeer-Gray-Eyebrows.png"},
  {item_id: 75, image_layer: "UghNoMouth.png"},
  {item_id: 76, image_layer: "WarmThermal-GrayBlue-LongSlvShirt.png"},
  {item_id: 77, image_layer: "WarmThermal-Snow-LongSleevedShirt.png"},
  {item_id: 78, image_layer: "WeddingConcerto-Ivory-BabyGrandPiano.png"},
  {item_id: 79, image_layer: "WIPBackground_Equipable.png"},
  {item_id: 80, image_layer: "WIP-Boots.png"},
  {item_id: 81, image_layer: "WIPDollyBowHair.png"},
  {item_id: 82, image_layer: "WIPfdaf.png"},
  {item_id: 83, image_layer: "WIPfjdkal.png"}
])
Item.create!([
  {name: "BuddingBeat-PeonyPink-Headphones"},
  {name: "BuddingBeat-White-Headphones"},
  {name: "CheckeredPuff-Purple-Scarf"},
  {name: "CheckeredPuff-Red-Scarf"},
  {name: "ElissasTresses-OrangeCaramel-Hairstyle"},
  {name: "Rodeo-CherryRed-Boots"},
  {name: "SkyeERCitizen-Navy-TracksuitJacket"},
  {name: "SugarlessCandy-Lavender-PigtailsHairstyle"},
  {name: "Background_Equipable"},
  {name: "BehindTheBlossoms-Auburn-Eyes"},
  {name: "BehindTheBlossoms-Blush-Makeup"},
  {name: "BehindTheBlossoms-Chestnut-Eyebrows"},
  {name: "BehindTheBlossomsFloppy-Lavender-KnitSweater"},
  {name: "BehindTheBlossomsFloppy-Pink-KnitSweater"},
  {name: "BehindTheBlossoms-Lavender-Hairstyle"},
  {name: "BehindTheBlossoms-Pink-Hairstyle"},
  {name: "BehindTheBlossoms-Red-Glasses"},
  {name: "BehindTheBlues-SoftGray-Glasses"},
  {name: "BitOfABother-Mouth"},
  {name: "CalmingGaze-Eyes-GlassBlue"},
  {name: "CalmingGaze-SiennaBrown-Eyebrows"},
  {name: "CheekyGrin-Mouth"},
  {name: "CheerfulGlint-AshBrown-Eyebrows"},
  {name: "CheerfulGlint-SkyBlue-Eyes"},
  {name: "ChipperUpbeatNatural-ForestGreen-Eyes"},
  {name: "DecidedlySatisfiedSmile-Mouth"},
  {name: "Disappearing_Bra"},
  {name: "Disappearing_Briefs"},
  {name: "Disappearing_Panties"},
  {name: "DraconianRule-Crimson-Eyebrows"},
  {name: "DraconianRule-Crimson-Eyes"},
  {name: "FleepTheCloudsheep-HoveringPose"},
  {name: "GentlyCurious-Blush-Makeup"},
  {name: "GentlyCuriousGaze-AshBrown-Eyebrows"},
  {name: "GentlyCuriousGaze-LilypadGreen-Eyes"},
  {name: "GentlyCurious-Mouth"},
  {name: "GrumpySpectre-Indigo-Eyes"},
  {name: "GrumpySpectre-Indigo-Face"},
  {name: "HomecomingTrail-Background"},
  {name: "Mischeivous-Mouth"},
  {name: "MischeivousThought-AgateGreen-Eyes"},
  {name: "MischeivousThought-AshBrown-Eyebrows"},
  {name: "PeppyPreppy-Auburn-PonytailHairstyle"},
  {name: "PeppyPreppy-Raspberry-PonytailHairstyle"},
  {name: "Piqued-Mouth"},
  {name: "ReubenStyledSporty-PaleFawn-Hairstyle"},
  {name: "RolledCuff-MedBlue-Jeans"},
  {name: "SemiSheenLycra-Black-Tights"},
  {name: "SemiSheenLycra-Silver-Tights"},
  {name: "SereneKindess-Flushed-EyeshdwNBlushMakeup"},
  {name: "SereneKindess-SpokenGently-Mouth"},
  {name: "SereneKindness-OceanBlue-Eyes"},
  {name: "SereneKindness-RedBrown-Eyebrows"},
  {name: "ShyPeep-Mouth"},
  {name: "SkyeERCitizen-PeriwinkleNWhite-Blouse"},
  {name: "SkyeERCitizen-PeriwinkleNWhite-Loafers"},
  {name: "SkyeERCitizen-PeriwinkleNWhite-Skirt"},
  {name: "SkyeERCitizen-PeriwinkleNWhite-Stockings"},
  {name: "SkyeERCitizen-PinkNWhite-Blouse"},
  {name: "SkyeERCitizen-PinkNWhite-Shoes"},
  {name: "SkyeERCitizen-PinkNWhite-Skirt"},
  {name: "SkyeERCitizen-PinkNWhite-Stockings"},
  {name: "SkyeERCitizenUniform-Navy-DressShirt"},
  {name: "SkyeERCitizenUniform-Navy-Jacket"},
  {name: "SkyeERCitizenUniform-Navy-Loafers"},
  {name: "SkyeERCitizenUniform-Navy-Slacks"},
  {name: "SmilingToMyself-Mouth"},
  {name: "SpeakingContentedly-Mouth"},
  {name: "SugarlessCandy-LavenderDrop-HeartUGazeEyes"},
  {name: "TobiasHeroic-Brown-Hairstyle"},
  {name: "TomasSmooth-HighlightedChestnut-Hairstyle"},
  {name: "TrustingEyes-Gray-Eyebrows"},
  {name: "TrustingPeer-AgateGreen-Eyes"},
  {name: "TrustingPeer-Gray-Eyebrows"},
  {name: "UghNoMouth"},
  {name: "WarmThermal-GrayBlue-LongSlvShirt"},
  {name: "WarmThermal-Snow-LongSleevedShirt"},
  {name: "WeddingConcerto-Ivory-BabyGrandPiano"},
  {name: "WIPBackground_Equipable"},
  {name: "WIP-Boots"},
  {name: "WIPDollyBowHair"},
  {name: "WIPfdaf"},
  {name: "WIPfjdkal"}
])